# Generated by Django 3.1.7 on 2021-05-05 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Лист ожидания',
                'verbose_name_plural': 'Листы ожидания',
            },
        ),
    ]
