# Generated by Django 3.1.7 on 2021-05-05 16:29

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Продукты - Отчёт',
                'verbose_name_plural': 'Продукты - Отчёты',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
    ]
