# Generated by Django 3.1.7 on 2021-05-08 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentProductQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_date', models.DateTimeField(verbose_name='Актуальная дата')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('type', models.CharField(choices=[('+', 'Приход'), ('-', 'Расход')], max_length=255, verbose_name='Тип движения')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_quantity', to='products.product', verbose_name='Товар')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_date', models.DateTimeField(verbose_name='Актуальная дата')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Стоимость')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_price', to='products.product', verbose_name='Товар')),
            ],
        ),
    ]
