# Generated by Django 3.1.7 on 2021-05-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentproductquantity_actual_date_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentproductquantity',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
    ]
