# Generated by Django 3.1.7 on 2021-05-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20210508_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentproductprice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Стоимость'),
        ),
    ]
