# Generated by Django 3.1.7 on 2021-05-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20210508_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentproductquantity',
            name='actual_date',
            field=models.DateField(verbose_name='Актуальная дата'),
        ),
        migrations.AlterField(
            model_name='documentproductquantity',
            name='actual_date_doc',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата поведения документа'),
        ),
    ]
