# Generated by Django 3.1.7 on 2021-05-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20210508_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentproductquantity',
            name='is_return',
            field=models.BooleanField(default=False, verbose_name='Возврат'),
        ),
        migrations.AddField(
            model_name='documentproductquantity',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Стоимость'),
        ),
    ]
