# Generated by Django 3.1.7 on 2021-07-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20210512_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentproductprice',
            options={'verbose_name': 'Регистр цен', 'verbose_name_plural': 'Регистры цен'},
        ),
        migrations.AlterModelOptions(
            name='documentproductquantity',
            options={'verbose_name': 'Документ учёта количества продуктов', 'verbose_name_plural': 'Документы учёта количества продуктов'},
        ),
    ]
