# Generated by Django 3.1.7 on 2021-05-05 16:29

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBoard',
            fields=[
            ],
            options={
                'verbose_name': 'Доска заказов',
                'verbose_name_plural': 'Доска заказов',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('order.order',),
        ),
    ]
