# Generated by Django 3.1.7 on 2021-05-15 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
            ],
            options={
                'verbose_name': 'Рассылка посетителям',
                'verbose_name_plural': 'Рассылки посетителям',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('consultation.diagnostic',),
        ),
        migrations.AlterModelOptions(
            name='diagnostic',
            options={'verbose_name': 'Заявка клиента', 'verbose_name_plural': 'Заявки клиентов'},
        ),
    ]
