# Generated by Django 3.1.7 on 2021-05-05 16:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.SlugField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('date_of_reg', models.DateTimeField(blank=True, null=True, verbose_name='Дата оформления заказа')),
                ('amount', models.FloatField(default=0, verbose_name='Цена')),
                ('status', models.CharField(blank=True, choices=[('new_order', 'Новый заказ'), ('wait_buy', 'В ожидании оплаты'), ('assembly', 'В процессе сборки'), ('ready', 'Готов к выдачи'), ('issued', 'Выдан')], default='new_order', max_length=255, null=True, verbose_name='Статус заказа')),
                ('buy', models.CharField(blank=True, choices=[('card', 'Оплата картой - онлайн'), ('cash', 'Оплата наличными')], max_length=255, null=True, verbose_name='Вид оплаты')),
                ('type_delivery', models.CharField(blank=True, choices=[('pickup', 'Самовывоз'), ('delivery', 'Доставка')], max_length=255, null=True, verbose_name='Вид доставки')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cart.cart', verbose_name='Корзина')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='store.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
