# Generated by Django 3.1.7 on 2021-05-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('new_order', 'Новый заказ'), ('wait_buy', 'В ожидании оплаты'), ('assembly', 'В процессе сборки'), ('ready', 'Готов к выдачи'), ('issued', 'Выдан'), ('canceled', 'Отменён')], default='new_order', max_length=255, null=True, verbose_name='Статус заказа'),
        ),
    ]
