# Generated by Django 3.1.7 on 2021-05-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210515_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='key',
            field=models.CharField(default=5248086732, max_length=10, verbose_name='Код заказа'),
        ),
    ]
