# Generated by Django 3.1.7 on 2021-05-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_confirm',
            field=models.BooleanField(default=False, verbose_name='Подтвержден'),
        ),
        migrations.AlterField(
            model_name='order',
            name='key',
            field=models.CharField(default=4663440613, max_length=10, verbose_name='Код заказа'),
        ),
    ]
