# Generated by Django 3.1.7 on 2021-05-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210523_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='key',
            field=models.CharField(default='5916600811', max_length=10, unique=True, verbose_name='Код заказа'),
        ),
    ]
