# Generated by Django 3.1.7 on 2021-05-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210523_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='key',
            field=models.CharField(default='9018433742', max_length=10, unique=True, verbose_name='Код заказа'),
        ),
        migrations.DeleteModel(
            name='OrderConfirmed',
        ),
    ]
