# Generated by Django 3.1.7 on 2021-06-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210529_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='key',
            field=models.CharField(default='dc529adb-b', max_length=10, unique=True, verbose_name='Код заказа'),
        ),
    ]
