# Generated by Django 3.1.7 on 2021-07-16 07:11

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20210613_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='key',
            field=models.CharField(default=order.models.random_key_order, max_length=10, unique=True, verbose_name='Код заказа'),
        ),
    ]
