# Generated by Django 3.1.7 on 2021-05-05 16:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Семантический URL')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('article', models.CharField(max_length=35, unique=True, verbose_name='Артикул')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('description', models.TextField(blank=True, max_length=3500, null=True, verbose_name='Описание')),
                ('active', models.BooleanField(default=True, verbose_name='Отображать')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.brand', verbose_name='Производитель')),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductUserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(default=0, verbose_name='Оценка')),
                ('favorite', models.BooleanField(default=False, verbose_name='Понравившийся')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action', to='products.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отношение Пользователь - Продукт',
                'verbose_name_plural': 'Отношения Пользователь - Продукт',
            },
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('type_buy', models.CharField(blank=True, choices=[('Под заказ', 'Под заказ (14 дней)'), ('В магазине', 'Покупка в магазине')], max_length=255, null=True, verbose_name='Вид покупки')),
                ('delivery', models.BooleanField(blank=True, default=False, null=True, verbose_name='Доставка')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Информация о товаре',
                'verbose_name_plural': 'Информация о товарах',
            },
        ),
        migrations.CreateModel(
            name='ProductCharacteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Характеристика')),
                ('decimal_value', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='Числовое значение')),
                ('text_value', models.CharField(blank=True, max_length=15, null=True, verbose_name='Текстовое значение')),
                ('unit', models.CharField(blank=True, choices=[('Кг', 'Кг'), ('Вт', 'Вт'), ('кВт', 'кВт'), ('Шт', 'Шт'), ('См', 'См'), ('М', 'М'), ('мм', 'мм'), ('м2', 'м2'), ('Л', 'Л'), ('км\\ч', 'км\\ч')], max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic', to='products.product')),
            ],
            options={
                'verbose_name': 'Характеристика товара',
                'verbose_name_plural': 'Характеристики товаров',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='uploads/products/%y/%m/%d/', verbose_name='Картинка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_discount', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Размер скидки в %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала действия скидки')),
                ('date_finish', models.DateTimeField(verbose_name='Дата окончания действия скидки')),
                ('products', models.ManyToManyField(related_name='discount', to='products.Product', verbose_name='Продукты на которые распространяется скидка')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Комментарий')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='products.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-date'],
            },
        ),
    ]
