# Generated by Django 3.1.7 on 2021-05-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210512_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Доставка'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_buy',
            field=models.CharField(blank=True, choices=[('Под заказ', 'Под заказ (14 дней)'), ('В магазине', 'Покупка в магазине')], max_length=255, null=True, verbose_name='Вид покупки'),
        ),
    ]
