# Generated by Django 3.1.7 on 2021-05-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210516_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery',
            field=models.BooleanField(default=False, verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_buy',
            field=models.CharField(choices=[('Под заказ', 'Под заказ (14 дней)'), ('В магазине', 'Покупка в магазине')], default=1, max_length=255, verbose_name='Вид покупки'),
            preserve_default=False,
        ),
    ]
