# Generated by Django 3.1.7 on 2021-05-20 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210516_2208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductInfo',
        ),
    ]
