# Generated by Django 3.1.7 on 2021-05-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_productinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Наименование скидки'),
            preserve_default=False,
        ),
    ]
