# Generated by Django 3.1.7 on 2021-06-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcharacteristic',
            name='text_value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текстовое значение'),
        ),
    ]
